In [23]:
import requests
import json
import bs4
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn
import re
import time
import itertools
from fantasyAnalytics import extractData as ed
from fantasyAnalytics import loadData as ld
from fantasyAnalytics import loadProjections as lp

%autoreload 2
%matplotlib inline

## Load Season Data

In [15]:
ld.save_week_data(11)

In [16]:
df_season = ld.get_season_df(1,11)

In [17]:
df_season.head()

,week,name,position,team,opponent,pass_yds,pass_td,int,rush_yds,rush_td,rec_yds,rec_td,fum_td,2pt,fum_lost,points
0,1,Andrew Luck,QB,IND,DET,385,4,-,21,-,-,-,-,1,-,35.50
1,1,Drew Brees,QB,NO,OAK,423,4,-,5,-,-,-,-,-,1,31.42
2,1,DeAngelo Williams,RB,PIT,@WAS,-,-,-,143,2,28,-,-,-,-,29.10
3,1,Alex Smith,QB,KC,SD,363,2,1,15,1,-,-,-,-,-,28.02
4,1,Brandin Cooks,WR,NO,OAK,-,-,-,11,-,143,2,-,-,-,27.40

In [5]:
df_season[df_season.name=="LeGarrette Blount"][["week", "name", "opponent", "points"]]

     week               name opponent  points
72      1  LeGarrette Blount     @ARI    11.0
23      2  LeGarrette Blount      MIA    18.3
16      3  LeGarrette Blount      HOU    22.5
126     4  LeGarrette Blount      BUF     5.8
72      5  LeGarrette Blount     @CLE     9.7
43      6  LeGarrette Blount      CIN    13.0
3       7  LeGarrette Blount     @PIT    25.4
71      8  LeGarrette Blount     @BUF    10.3
329     9  LeGarrette Blount      Bye     0.0
8      10  LeGarrette Blount      SEA    24.9

## Load Projection Data

In [3]:
weeks=range(11,12)
for week in weeks:
    lp.save_week_projections(week)

In [4]:
df_proj = lp.get_season_df(1,11)

#### Scratch

In [22]:
# set player name
name = "Travis Kelce"

# get projected points for player
df_proj[df_proj.name==name]

,week,name,position,team,opponent,pass_yds,pass_td,int,rush_yds,rush_td,rec_yds,rec_td,fum_td,2pt,fum_lost,points
76,1,Travis Kelce,TE,KC,SD,0.0,0.0,0.0,0.0,0.0,51.0,1.0,0,0.0,0.0,11.10
55,2,Travis Kelce,TE,KC,@HOU,0.0,0.0,0.0,0.0,0.0,53.0,1.0,0,0.0,0.0,11.30
121,3,Travis Kelce,TE,KC,NYJ,1.0,0.0,0.0,1.0,0.0,65.0,0.0,0,0.0,0.0,6.64
71,4,Travis Kelce,TE,KC,@PIT,0.0,0.0,0.0,1.0,0.0,52.0,1.0,0,0.0,0.0,11.30
651,5,Travis Kelce,TE,KC,Bye,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.00
156,6,Travis Kelce,TE,KC,@OAK,0.0,0.0,0.0,0.0,0.0,48.0,0.0,0,0.0,0.0,4.80
73,7,Travis Kelce,TE,KC,NO,0.0,0.0,0.0,0.0,0.0,47.0,1.0,0,0.0,0.0,10.70
136,8,Travis Kelce,TE,KC,@IND,0.0,0.0,0.0,0.0,0.0,45.0,0.0,0,0.0,0.0,4.50
56,9,Travis Kelce,TE,KC,JAX,0.0,0.0,0.0,0.0,0.0,49.0,1.0,0,0.0,0.0,10.90
140,10,Travis Kelce,TE,KC,@CAR,0.0,0.0,0.0,0.0,0.0,50.0,0.0,0,0.0,0.0,5.00
62,11,Travis Kelce,TE,KC,TB,0.0,0.0,0.0,0.0,0.0,45.0,1.0,0,0.0,0.0,10.50

In [21]:
# get actual points for player
df_season[df_season.name==name]

,week,name,position,team,opponent,pass_yds,pass_td,int,rush_yds,rush_td,rec_yds,rec_td,fum_td,2pt,fum_lost,points
109,1,Travis Kelce,TE,KC,SD,-,-,-,-,-,74,-,-,-,-,7.4
180,2,Travis Kelce,TE,KC,@HOU,-,-,-,-,-,34,-,-,-,-,3.4
41,3,Travis Kelce,TE,KC,NYJ,-,-,-,-,-,89,1,-,-,-,14.9
92,4,Travis Kelce,TE,KC,@PIT,-,-,-,-,-,23,1,-,-,-,8.3
607,5,Travis Kelce,TE,KC,Bye,-,-,-,-,-,-,-,-,-,-,0.0
169,6,Travis Kelce,TE,KC,@OAK,-,-,-,-,-,32,-,-,-,-,3.2
162,7,Travis Kelce,TE,KC,NO,-,-,-,-,-,24,-,-,-,-,2.4
29,8,Travis Kelce,TE,KC,@IND,-,-,-,-,-,101,1,-,-,-,16.1
116,9,Travis Kelce,TE,KC,JAX,0,0,0,0,0,58,0,0,0,0,5.8
128,10,Travis Kelce,TE,KC,@CAR,0,0,0,0,0,31,0,0,1,0,5.1
70,11,Travis Kelce,TE,KC,TB,0,0,0,-5,0,108,0,0,0,0,10.3

In [31]:
ed.defenses_against("TE").sort_values("mean")

   team  points_against       mean        std
29  ARI            24.2   2.688889   1.945151
23  BAL            35.3   3.922222   1.835605
27   KC            46.5   5.166667   3.049180
30  HOU            50.2   5.577778   5.342466
24  PHI            47.5   5.937500   4.209492
28  DEN            60.7   6.070000   4.481332
4    LA            55.4   6.155556   5.995230
14  CHI            64.1   6.410000   4.978721
16   SF            64.2   6.420000   5.991995
10   NE            65.9   6.590000   4.126459
18  JAX            68.3   6.830000   4.906470
20  SEA            64.0   7.111111   5.840258
6   PIT            73.6   7.360000   4.096394
3    SD            67.9   7.544444   4.326116
26   NO            75.9   7.590000   7.099992
5   NYG            76.6   7.660000   4.716449
19  DAL            77.0   7.700000   5.775427
25  NYJ            69.4   7.711111   4.985089
9   MIN            79.3   7.930000   4.270584
11  BUF            72.2   8.022222   8.670608
21  TEN            88.6   8.054545   6.649867
13  MIA            76.6   8.511111   6.996328
31  WAS            86.3   8.630000   6.358380
8    TB            78.4   8.711111   6.870488
15  OAK            93.1   9.310000   7.683236
22  IND            93.9   9.390000   5.704861
1    GB            96.6   9.660000   6.622554
12  CAR           110.4  11.040000   7.886444
17  ATL            90.9  11.362500   4.430717
7   CLE           125.6  11.418182  11.569513
2   CIN           116.2  11.620000   9.156637
0   DET           117.1  11.710000   7.250050

In [30]:
ed.position_against_team("TE", "DEN")

     week              name team position opponent  points
112     1        Greg Olsen  CAR       TE     @DEN     7.3
174     2        Jack Doyle  IND       TE     @DEN     3.7
205     2      Dwayne Allen  IND       TE     @DEN     2.5
181     3       C.J. Uzomah  CIN       TE      DEN     3.1
117     4     Cameron Brate   TB       TE      DEN     6.7
183     5     Austin Hooper  ATL       TE     @DEN     1.4
230     5       Jacob Tamme  ATL       TE     @DEN     0.1
38      6      Hunter Henry   SD       TE      DEN    14.3
216     6     Antonio Gates   SD       TE      DEN     1.6
146     7  C.J. Fiedorowicz  HOU       TE     @DEN     3.5
196     7      Ryan Griffin  HOU       TE     @DEN     1.3
84      8     Antonio Gates   SD       TE     @DEN     9.3
193     8      Hunter Henry   SD       TE     @DEN     1.4
203     9     Clive Walford  OAK       TE      DEN     1.3
223     9     Mychal Rivera  OAK       TE      DEN     0.6
165    10      Coby Fleener   NO       TE      DEN     2.6

In [29]:
df_season[(df_season.team=="WAS") & (df_season.position=="WR") & (df_season.points != 0)]

,week,name,position,team,opponent,pass_yds,pass_td,int,rush_yds,rush_td,rec_yds,rec_td,fum_td,2pt,fum_lost,points
80,1,DeSean Jackson,WR,WAS,PIT,-,-,-,-,-,102,-,-,-,-,10.2
136,1,Jamison Crowder,WR,WAS,PIT,-,-,-,-,-,58,-,-,-,-,5.8
145,1,Pierre Garcon,WR,WAS,PIT,-,-,-,-,-,51,-,-,-,-,5.1
238,1,Josh Doctson,WR,WAS,PIT,-,-,-,-,-,9,-,-,-,-,0.9
83,2,Jamison Crowder,WR,WAS,DAL,-,-,-,-,-,39,1,-,-,-,9.9
134,2,Josh Doctson,WR,WAS,DAL,-,-,-,-,-,57,-,-,-,-,5.7
162,2,DeSean Jackson,WR,WAS,DAL,-,-,-,-,-,40,-,-,-,-,4.0
207,2,Pierre Garcon,WR,WAS,DAL,-,-,-,-,-,25,-,-,-,-,2.5
287,2,Ryan Grant,WR,WAS,DAL,-,-,-,-,-,5,-,-,-,-,0.5
39,3,DeSean Jackson,WR,WAS,@NYG,-,-,-,-,-,96,1,-,-,-,15.6
49,3,Jamison Crowder,WR,WAS,@NYG,-,-,-,-,-,78,1,-,-,-,13.8
122,3,Pierre Garcon,WR,WAS,@NYG,-,-,-,-,-,59,-,-,-,-,5.9
154,4,Pierre Garcon,WR,WAS,CLE,-,-,-,-,-,39,-,-,-,-,3.9
191,4,Jamison Crowder,WR,WAS,CLE,-,-,-,-,-,21,-,-,-,-,2.1
255,4,DeSean Jackson,WR,WAS,CLE,-,-,-,-,-,5,-,-,-,-,0.5
56,5,Pierre Garcon,WR,WAS,@BAL,-,-,-,-,-,56,1,-,-,-,11.6
142,5,Jamison Crowder,WR,WAS,@BAL,-,-,-,-,-,35,-,-,-,-,3.5
144,5,DeSean Jackson,WR,WAS,@BAL,-,-,-,-,-,35,-,-,-,-,3.5
206,5,Rashad Ross,WR,WAS,@BAL,-,-,-,-,-,8,-,-,-,-,0.8
69,6,Jamison Crowder,WR,WAS,PHI,-,-,-,-9,-,52,1,-,-,-,10.3
97,6,Pierre Garcon,WR,WAS,PHI,-,-,-,-,-,77,-,-,-,-,7.7
126,6,DeSean Jackson,WR,WAS,PHI,-,-,-,-,-,55,-,-,-,-,5.5
66,7,Jamison Crowder,WR,WAS,@DET,-,-,-,-,-,108,-,-,-,-,10.8
147,7,DeSean Jackson,WR,WAS,@DET,-,-,-,-,-,35,-,-,-,-,3.5
167,7,Pierre Garcon,WR,WAS,@DET,-,-,-,-,-,22,-,-,-,-,2.2
244,7,Ryan Grant,WR,WAS,@DET,-,-,-,-,-,5,-,-,-,-,0.5
26,8,Jamison Crowder,WR,WAS,@CIN,-,-,-,-,-,107,1,-,-,-,16.7
114,8,Pierre Garcon,WR,WAS,@CIN,-,-,-,-,-,67,-,-,-,-,6.7
131,8,DeSean Jackson,WR,WAS,@CIN,-,-,-,-,-,48,-,-,-,-,4.8
188,8,Ryan Grant,WR,WAS,@CIN,-,-,-,-,-,17,-,-,-,-,1.7
66,10,Jamison Crowder,WR,WAS,MIN,0,0,0,7,0,37,1,0,0,0,10.4
86,10,Pierre Garcon,WR,WAS,MIN,0,0,0,0,0,81,0,0,0,0,8.1
159,10,Maurice Harris,WR,WAS,MIN,0,0,0,0,0,28,0,0,0,0,2.8
15,11,Pierre Garcon,WR,WAS,GB,0,0,0,0,0,116,1,0,0,0,17.6
19,11,Jamison Crowder,WR,WAS,GB,0,0,0,0,0,102,1,0,0,0,16.2
61,11,DeSean Jackson,WR,WAS,GB,0,0,0,0,0,51,1,0,0,0,11.1
205,11,Maurice Harris,WR,WAS,GB,0,0,0,0,0,14,0,0,0,0,1.4
230,11,Ryan Grant,WR,WAS,GB,0,0,0,0,0,4,0,0,0,0,0.4